[package]
name = "brewfile-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
brewfile-parser = { path = '../brewfile-parser' }
brewfile-traits = { path = '../brewfile-traits' }
nom = "8.0.0"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.95"

